### ISSUE TITLE
Bogus error

### ISSUE THREAD

**Issue by m0ppers** [jsteemann/jshund#1]
develop@vmdevelop:~/Dokumente/workspace/topconew> cat wurst.js
var bumms = {};
(function hihi(bumms) {
    bumms.wurst = function() {
        return findIndexByItemNumber(2);
    };
    var findIndexByItemNumber = function(item_number) {
        return item_number;
    };
}(bumms));

console.log(bumms.wurst());
develop@vmdevelop:~/Dokumente/workspace/topconew> node wurst.js
2
develop@vmdevelop:~/Dokumente/workspace/topconew> /home/develop/jshund/jshund wurst.js
wurst.js:6: unused local variable 'findIndexByItemNumber'

**Comment by jsteemann** [comment]
'tis because findIndexByItemNumber is declared in the global scope after it is used in the inner scope.
Will fix eventually.

**Comment by m0ppers** [comment]
ok better example:

``` js
angular.module('x').factory('hundService', function() {
    var hundService = {};
    hundService.serviceMethod = function(x) {
        return findIndexByItemNumber(x);
    }

    var findIndexByItemNumber = function(item_number) {
        return item_number;
    };
    return hundService;
});
```

This is an example (standard) factory for angular services. The first example was of course very hackish ;)

**Comment by jsteemann** [comment]
It's fine. I think I need to fix that variables can be declared after they are used (in terms of line numbers, the scanner just goes from start to end of a script).

**Comment by jsteemann** [comment]
Should be fixed.
